# Generated by Django 4.2.3 on 2023-08-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_userid_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='createdOn',
            new_name='CreatedOn',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastModified',
            new_name='LastModified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='UserName',
        ),
    ]
