# Generated by Django 4.2.3 on 2023-08-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_id_movie_id_rename_createdon_user_createdon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='CreatedOn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='LastModified',
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
